import { Platform, StatusBar, StyleSheet } from 'react-native';
import { colors } from '../../../utils/colors';
import fonts from '../../../assets/fonts';

export const styles = StyleSheet.create({
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    padding: 15,
    backgroundColor: colors.white,
    justifyContent: 'space-between',
    elevation: 20,
    shadowColor: colors.grey,
    shadowOffset: { height: 2, width: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    paddingBottom: 25,
    marginBottom: -10,
  },
  headerBox: {
    marginLeft: 12,
    alignItems: 'center',
    flexDirection: 'row',
    flex: 1,
  },
  inputBox: {
    width: '83%',
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  input: {
    flex: 1,
    backgroundColor: 'transparent',
    borderRadius: 30,
    fontSize: 14,
    fontFamily: fonts.regular,
    color: colors.black,
    borderWidth: 1,
    borderColor: colors.lightGrey,
    paddingRight: 40,
    paddingHorizontal: 18,
    paddingVertical: 0,
    height: 50,
  },
  sendButton: {
    borderRadius: 50,
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    paddingHorizontal: 22,
    justifyContent: 'flex-start',
    backgroundColor: colors.white,
    alignItems: 'center',
    flexDirection: 'row',
    elevation: 10,
    shadowColor: colors.grey,
    shadowOffset: { height: 2, width: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    paddingTop: Platform.OS === 'ios' ? StatusBar.currentHeight + 30 : 5,
    paddingBottom: 10,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 10,
    marginLeft: 10,
    marginRight: 10,
    resizeMode: 'stretch',
  },
  uploadBtn: {
    width: 35,
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: 7,
    bottom: 7,
  },
  loader: {
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  sheetContainer: {
    backgroundColor: '#fff',
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  blockBtn: {
    borderWidth: 1,
    borderColor: colors.red,
    backgroundColor: 'transparent',
  },
});
